name: Build macOS Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🧠 PNG → ICNS Konvertierung (automatisch)
      - name: Generate .icns from PNG
        run: |
          echo "Generating icon.icns from src/icons/icon-1024.png ..."
          mkdir -p src/icons/icon.iconset
          sips -z 16 16     src/icons/icon-1024.png --out src/icons/icon.iconset/icon_16x16.png
          sips -z 32 32     src/icons/icon-1024.png --out src/icons/icon.iconset/icon_16x16@2x.png
          sips -z 32 32     src/icons/icon-1024.png --out src/icons/icon.iconset/icon_32x32.png
          sips -z 64 64     src/icons/icon-1024.png --out src/icons/icon.iconset/icon_32x32@2x.png
          sips -z 128 128   src/icons/icon-1024.png --out src/icons/icon.iconset/icon_128x128.png
          sips -z 256 256   src/icons/icon-1024.png --out src/icons/icon.iconset/icon_128x128@2x.png
          sips -z 256 256   src/icons/icon-1024.png --out src/icons/icon.iconset/icon_256x256.png
          sips -z 512 512   src/icons/icon-1024.png --out src/icons/icon.iconset/icon_256x256@2x.png
          sips -z 512 512   src/icons/icon-1024.png --out src/icons/icon.iconset/icon_512x512.png
          cp src/icons/icon-1024.png src/icons/icon.iconset/icon_512x512@2x.png
          iconutil -c icns src/icons/icon.iconset -o src/icons/icon.icns
          echo "✅ icon.icns created at src/icons/icon.icns"

      - name: Install dependencies
        run: npm install

      - name: Build macOS app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/*.dmg

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
